### PR TITLE
fix(cpo): Reduce CPO cluster permissions

### LINKED ISSUE #1026: Security MVP: Reduce CPO's cluster permissions
Currently, the CPO has attached `ClusterRole` with the following permissions:
https://github.com/openshift/hypershift/blob/e4b844b9d2c545f24b2ea64bad14257661162407/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L2058-L2089

We should scope-down the actions that it can perform on these resources, or convert the `ClusterRole` to a namespace-scoped `Role` to reduce the area of effect within the management cluster.

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
- Removes CPO's ClusterRole/ClusterRoleBinding
- Updates CPO's securitycontext from explicit to use default
- Adjusts CPO's existing Role
- Creates additional Role/RoleBinding for ingress service reads
- Creates additional Role/RoleBinding for ingress operator ingresscontroller crud
- Conditionally activates awsprivatelink controllers based on Route capability

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #1026 

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

**Note**
Have verified that control plane is able to get rolled out with these changes.
```
NAME                                                 READY   STATUS      RESTARTS   AGE
catalog-operator-7fc9847d5f-85fmz                    2/2     Running     0          9m23s
certified-operators-catalog-675b86bbbf-9tvxd         1/1     Running     0          9m24s
certified-operators-catalog-rollout-27420333-57mbs   0/1     Completed   0          4m5s
cloud-controller-manager-7c75877b89-h2p2b            1/1     Running     0          6m15s
cloud-controller-manager-7c75877b89-htcjp            1/1     Running     0          6m15s
cloud-controller-manager-7c75877b89-tvdxs            1/1     Running     0          6m15s
cluster-api-57987f99bd-c4sq5                         1/1     Running     0          9m46s
cluster-api-57987f99bd-g72bh                         1/1     Running     0          9m46s
cluster-api-57987f99bd-tn8pq                         1/1     Running     0          9m46s
cluster-autoscaler-7c9fbd559c-mhbws                  1/1     Running     0          9m17s
cluster-policy-controller-8445b79ccc-lmx7k           1/1     Running     0          9m26s
cluster-policy-controller-8445b79ccc-w6stl           1/1     Running     0          9m26s
cluster-policy-controller-8445b79ccc-zl9wx           1/1     Running     0          9m26s
cluster-version-operator-6c568f5f99-7jf8q            2/2     Running     0          9m26s
community-operators-catalog-6df994c5b5-vccpp         1/1     Running     0          9m23s
community-operators-catalog-rollout-27420333-rtwtv   0/1     Completed   0          4m5s
control-plane-operator-87bf8457f-q69q5               1/1     Running     0          9m45s
etcd-hide-test-5-88mzsjs4h4                          3/3     Running     0          8m15s
etcd-hide-test-5-bm4475hd78                          3/3     Running     0          7m59s
etcd-hide-test-5-wxnkvr8lvw                          3/3     Running     0          10m
etcd-operator-84fd47d866-65qqc                       4/4     Running     4          10m
etcd-operator-84fd47d866-d7nw7                       4/4     Running     4          10m
etcd-operator-84fd47d866-ksqgf                       4/4     Running     4          10m
etcd-restore-operator-cert-creator-tddwg             0/1     Completed   0          10m
hosted-cluster-config-operator-cc7d7644d-9c9xx       1/1     Running     0          9m24s
ignition-server-cbfcd686d-5lj92                      1/1     Running     0          9m44s
ignition-server-cbfcd686d-v4dmb                      1/1     Running     0          9m44s
ignition-server-cbfcd686d-vh8xd                      1/1     Running     0          9m45s
ingress-operator-59986b6f4c-xpkx6                    2/2     Running     0          9m25s
konnectivity-agent-746dc879b9-77twf                  1/1     Running     0          9m29s
konnectivity-agent-746dc879b9-djvtg                  1/1     Running     0          9m29s
konnectivity-agent-746dc879b9-t9nd8                  1/1     Running     0          9m29s
konnectivity-server-6f8d7d8fc-94jdf                  1/1     Running     0          9m29s
kube-apiserver-58457cddb9-26jgb                      2/2     Running     2          9m28s
kube-apiserver-58457cddb9-rbjx8                      2/2     Running     2          9m28s
kube-apiserver-58457cddb9-v672v                      2/2     Running     2          9m28s
kube-controller-manager-5f74d96685-4xcsd             1/1     Running     0          9m28s
kube-controller-manager-5f74d96685-v2rlp             1/1     Running     0          9m28s
kube-controller-manager-5f74d96685-wwj4c             1/1     Running     0          9m28s
kube-scheduler-8c5d9779f-l9wtd                       1/1     Running     0          9m28s
kube-scheduler-8c5d9779f-vnh8d                       1/1     Running     0          9m28s
kube-scheduler-8c5d9779f-vqxcd                       1/1     Running     0          9m28s
machine-approver-6fd5f798df-zxfft                    1/1     Running     0          9m16s
oauth-openshift-6b8964bbc9-27gcn                     1/1     Running     0          9m26s
oauth-openshift-6b8964bbc9-bsvwd                     1/1     Running     0          9m26s
oauth-openshift-6b8964bbc9-mvxnc                     1/1     Running     0          9m26s
olm-collect-profiles-27420333-48v74                  0/1     Completed   0          4m5s
olm-operator-68c587cf9f-dc6zs                        2/2     Running     0          9m22s
openshift-apiserver-67dc55bc7-6jpwb                  2/2     Running     0          9m28s
openshift-apiserver-67dc55bc7-z6k2x                  2/2     Running     0          9m27s
openshift-apiserver-67dc55bc7-zf7bk                  2/2     Running     0          9m27s
openshift-controller-manager-7849ff8459-9z8r4        1/1     Running     0          9m26s
openshift-controller-manager-7849ff8459-cld5l        1/1     Running     0          9m26s
openshift-controller-manager-7849ff8459-lrpbd        1/1     Running     0          9m26s
openshift-oauth-apiserver-66686d6845-hrftp           1/1     Running     0          9m27s
openshift-oauth-apiserver-66686d6845-mrvgp           1/1     Running     0          9m27s
openshift-oauth-apiserver-66686d6845-nfmvv           1/1     Running     0          9m27s
packageserver-595c7c896b-52zh4                       2/2     Running     0          9m22s
packageserver-595c7c896b-8bc4w                       2/2     Running     0          9m22s
packageserver-595c7c896b-q7qzt                       2/2     Running     0          9m22s
redhat-marketplace-catalog-56c9658865-wg99s          1/1     Running     0          9m23s
redhat-marketplace-catalog-rollout-27420333-rnjlr    0/1     Completed   0          4m5s
redhat-operators-catalog-65756747dd-ds4bx            1/1     Running     0          9m23s
redhat-operators-catalog-rollout-27420333-sg9q2      0/1     Completed   0          4m5s
```

### CODE REVIEW

File: hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go [hunk 1]
```diff
@@ -2131,6 +2064,11 @@ func reconcileControlPlaneOperatorRole(role *rbacv1.Role) error {
 			Resources: []string{"*"},
 			Verbs:     []string{"*"},
 		},
+		{
+			APIGroups: []string{"rbac.authorization.k8s.io"},
```
Comment (rtheis) [inline hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:2068]: Can we scope down this RBAC authority further?

**Comment by sjenning** [comment]
From test run
```
Failed to watch *v1.IngressController: failed to list *v1.IngressController: ingresscontrollers.operator.openshift.io is forbidden: User "system:serviceaccount:e2e-clusters-2dhx9-example-99rbn:control-plane-operator" cannot list resource "ingresscontrollers" in API group "operator.openshift.io" in the namespace "openshift-ingress-operator"
```

File: hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go [hunk 2]
```diff
@@ -2050,65 +2046,20 @@ func reconcileControlPlaneOperatorDeployment(deployment *appsv1.Deployment, hc *
...
-			Resources: []string{"customresourcedefinitions"},
-			Verbs:     []string{"*"},
-		},
-		{
-			APIGroups: []string{"config.openshift.io"},
-			Resources: []string{"*"},
-			Verbs:     []string{"get", "list", "watch"},
-		},
-		{
-			APIGroups: []string{"operator.openshift.io"},
```
Comment (sjenning) [inline hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:2073]: This was allowing the watch of `IngressControllers` on the management cluster

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:2073]: Thanks! I will move this to an appropriate role/rolebiinding.

**Comment by hasueki** [comment]
Looks like I need to add all cruds for `ingresscontrollers`..
```
{"level":"error","ts":"2022-02-24T17:47:29Z","logger":"controller.hostedcontrolplane","msg":"Reconciler error","reconciler group":"hypershift.openshift.io","reconciler kind":"HostedControlPlane","name":"example-w7zx2","namespace":"e2e-clusters-jbxqv-example-w7zx2","error":"failed to update control plane: failed to reconcile private ingresscontroller: ingresscontrollers.operator.openshift.io is forbidden: User \"system:serviceaccount:e2e-clusters-jbxqv-example-w7zx2:control-plane-operator\" cannot create resource \"ingresscontrollers\" in API group \"operator.openshift.io\" in the namespace \"openshift-ingress-operator\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
```

**Comment by csrwng** [comment]
Yes we create and delete them
