### PR TITLE
fix(ho): Use v1alpha1 ownerRef for future CPO managed components

### LINKED ISSUE #1955: Upgrade path from 4.10 to 4.11 is broken with v1beta1 support
We’re running into issues with upgrades paths from 4.10 --> 4.11 using HO that’s v1beta1 capable. And it looks like the contributing factor is the move of components (cluster-autoscaler, ignition-server, machine-approver) that’s HO-managed to CPO-managed. Here’s what we're observing:
- HO (with v1beta1) reconciles 4.10 HC
- HO lays down owner references to objects that looks like:
```
  ownerReferences:
  - apiVersion: hypershift.openshift.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: HostedControlPlane
    name: 4-10
    uid: 7f48a7b0-dfba-4b90-9d63-135d2f7129de
```
- 4.10 HC deploys out successfully
- Now upgrade HC to 4.11
- 4.11 CPO tries to take ownership of these components by updating the owner references (note the difference in apiVersion):
```
  ownerReferences:
  - apiVersion: hypershift.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: HostedControlPlane
    name: 4-10
    uid: 7f48a7b0-dfba-4b90-9d63-135d2f7129de
```
- ^ But this is not happening with this error:
```
failed to update control plane: failed to reconcile autoscaler: failed to reconcile autoscaler role: Role.rbac.authorization.k8s.io \"cluster-autoscaler-management\" is invalid: metadata.ownerReferences: Invalid value: []v1.OwnerReference{v1.OwnerReference{APIVersion:\"hypershift.openshift.io/v1beta1\", Kind:\"HostedControlPlane\", Name:\"4-10\", UID:\"7f48a7b0-dfba-4b90-9d63-135d2f7129de\", Controller:(*bool)(0xc04d5f89b9), BlockOwnerDeletion:(*bool)(0xc04d5f89ba)}, v1.OwnerReference{APIVersion:\"hypershift.openshift.io/v1alpha1\", Kind:\"HostedControlPlane\", Name:\"4-10\", UID:\"7f48a7b0-dfba-4b90-9d63-135d2f7129de\", Controller:(*bool)(0xc04d5f89bb), BlockOwnerDeletion:(*bool)(0xc04d5f89bc)}}: Only one reference can have Controller set to true. Found \"true\" in references for 4-10 and 4-10
```
- We were able to get around this manually by removing the v1beta1 owner reference - then CPO was able to lay down it’s v1alpha1 owner reference to proceed.
- ^ This leads us to think that the fact the owner references have differing apiVersion , that’s treated as an addition to the ownerReferences annotation rather than a replace, which is causing issues.

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Updates HO to continue using `v1alpha1` ownerRefs for components (cluster-autoscaler, machine-approver, ignition-server) that will eventually move to CPO management. This will be the case for HCs < 4.12.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #1955 

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

File: hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go [hunk 1]
```diff
@@ -1395,6 +1399,11 @@ func (r *HostedClusterReconciler) reconcile(ctx context.Context, req ctrl.Reques
 
 	// Reconcile the Ignition server
 	if !controlplaneOperatorManagesIgnitionServer {
+		ownerRef := config.OwnerRefFrom(hcp)
+		if r.ReleaseVersion.Major == 4 && r.ReleaseVersion.Minor < 12 {
+			ownerRef.Reference.APIVersion = hyperv1alpha1.GroupVersion.String()
+		}
```
Comment (csrwng) [inline hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:1405]: nit: put this logic in a single function that can be referenced called from wherever it's needed

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go]: Extracted to common lib and added unit test

File: hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go [hunk 2]
```diff
@@ -132,9 +132,12 @@ type HostedClusterReconciler struct {
 	// 2) The OCP version being deployed is the latest version supported by Hypershift
 	HypershiftOperatorImage string
 
-	// releaseProvider looks up the OCP version for the release images in HostedClusters
+	// ReleaseProvider looks up the OCP version for the release images in HostedClusters
 	ReleaseProvider releaseinfo.ProviderWithRegistryOverrides
 
+	// ReleaseVersion is the OCP release image semver
+	ReleaseVersion semver.Version
```
Comment (csrwng) [inline hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:139]: @hasueki I don't think this belongs in the reconciler. The reconciler will be reconciling HostedClusters of potentially many different release versions.

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:139]: Ah gotcha, I was afraid that was the case. I went back and forth on where we can put this info. It seems like we don't want to do a registry lookup every time either.. Would it be ok if we add a new field in `HC.Status.Version.Desired{}`? Maybe `HC.Status.Version.Desired.Version`?
https://github.com/openshift/hypershift/blob/d1aaa9b3dee008976cf00657583fe96975ee7bb8/api/v1beta1/hostedcluster_types.go#L1264-L1270

Comment (csrwng) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:139]: The registry lookup is not bad, we use a cache that should result in a quick operation. 
https://github.com/openshift/hypershift/blob/d1aaa9b3dee008976cf00657583fe96975ee7bb8/hypershift-operator/main.go#L233

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:139]: Is the caching behavior different for images with tags vs digests? I think there were few convos on that for using digests for HO/CPO images. Is that the same case for this release image lookup? We use release images that may look like: `ocp-release:4.9.51-x86_64`

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:139]: Ah I see, it looks like it uses a different cache for release images vs the scenario I was thinking about:
- https://github.com/openshift/hypershift/blob/d1aaa9b3dee008976cf00657583fe96975ee7bb8/support/releaseinfo/cached_provider.go#L40
- https://github.com/openshift/hypershift/blob/d1aaa9b3dee008976cf00657583fe96975ee7bb8/support/util/imagemetadata.go#L50

I will adjust to do the release image lookup instead.

**Comment by enxebre** [comment]
/hold
to prevent ci from rerunning in this high prio [PR](https://github.com/openshift/hypershift/pull/1970#event-8078713237)

**Comment by hasueki** [comment]
@csrwng Updated based on your feedback. Please re-review when you get a chance.
