### PR TITLE
fix(cpo): Set restart annotation on multus-admission-controller

### LINKED ISSUE #376: Proposal: Enable control plane deployment restart on demand
Service providers need a way to restart control plane pods on demand (See https://github.com/openshift/hypershift/issues/236). When control plane pods reach a bad state, it should be possible to determine that this is the case through liveness probes and let the system restart them automatically. Any other bad state that is not detectable is a bug that should be fixed. However, reality is that there will be times when a restart of the pods is needed to clear wrong state. 

When using kubectl to restart a deployment through `kubectl rollout restart`, the result of the command is the addition of an annotation (`kubectl.kubernetes.io/restartedAt`) to the deployment's pod template: 
https://github.com/kubernetes/kubectl/blob/47df52af297ea787c44f3d4d7da11e7e4e0d83a8/pkg/polymorphichelpers/objectrestarter.go#L44-L52

For Hypershift, we can do something similar, in one of 2 ways:

1) We allow a `hypershift.openshift.io/restartedAt` annotation in the `HostedCluster` to be propagated to the `HostedControlPlane` and then to each deployment's pod template in the control plane. Then we can expose a similar command to the kubectl command in the hypershift CLI: `hypershift restart hostedcluster NAME -n NAMESPACE` that will populate this annotation.

2) We add a field to the spec of `HostedCluster` that allows us to either a) specify a restartedAt value, or b) an integer that can be incremented, resulting in a new `restartedAt` value we can store in status.

Given that this is not necessarily part of the spec of a HostedCluster, my preference would be to go with option 1.

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
With `multus-admission-controller` in the CP side for 4.12, it does not cycle when the HC/HCP restart annotation is applied. This change makes it so that CPO will set the restart annotation.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #376

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

File: control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go [hunk 1]
```diff
@@ -431,3 +434,29 @@ func isOVNSBDBExposedThroughHCPRouter(hcp *hyperv1.HostedControlPlane) bool {
...
+		}
+		return fmt.Errorf("failed retrieve deployment: %w", err)
+	}
+
+	patch := dep.DeepCopy()
+	podMeta := patch.Spec.Template.ObjectMeta
+	if podMeta.Annotations == nil {
+		podMeta.Annotations = map[string]string{}
+	}
+	podMeta.Annotations[hyperv1.RestartDateAnnotation] = c.AdditionalAnnotations[hyperv1.RestartDateAnnotation]
```
Comment (relyt0925) [inline control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go:455]: Will this get rereconciled and squashed by the cluster-network-operator?

Comment (a-dsouza) [reply control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go:455]: Tested this change--can confirm the `multus-admission-controller` pods restart successfully now when triggered with the HC `restart-date` annotation. Also cycled the `cluster-network-operator` pod to verify it won't squash the restart annotation on the `multus-admission-controller` deployment, and that does seem to be the case.

Comment (relyt0925) [reply control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go:455]: Awesome!!!! Approved
