### PR TITLE
Don't store machine payload in token secret for replace node pools

### LINKED ISSUE #1843: Disable MachineConfig payload in token secret for non-inplace upgrade NodePools
As result of performance testing at large scale, we noticed that the 4.11 HyperShift clusters running 375 HostedClusters with 12 NodePools each is causing mass KAS OOM kills on the management cluster KAS.

In 4.11, an additional Secret field, `payload`, was introduced in the ignition-server token Secret to support inplace upgrades, https://github.com/openshift/hypershift/pull/1290. This payload includes the entire MachineConfig content which is very large (`434229 bytes`). This is causing a scale regression for provider running HyperShift at large scale.

We should update the token secret reconciliation logic to omit the inclusion of this Secret value for non-inplace (replace) upgrade NodePools.

### PR DESCRIPTION
**Pull request by isco-rodriguez**
**What this PR does / why we need it**:
Storing the machine payload in the token secrets causes performance issues at a large scale. We can omit that field in replace upgrade node pools

**Which issue(s) this PR fixes**:
Fixes #1843
ref https://issues.redhat.com/browse/HOSTEDCP-604

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

File: ignition-server/controllers/tokensecret_controller.go [hunk 1]
```diff
@@ -284,11 +285,17 @@ func (r *TokenSecretReconciler) Reconcile(ctx context.Context, req ctrl.Request)
 		r.PayloadStore.Set(string(oldToken), CacheValue{Payload: payload, SecretName: tokenSecret.Name})
 	}
 
-	// Store the cached payload in the secret to be consumed by in place upgrades.
 	patch := tokenSecret.DeepCopy()
-	patch.Data[TokenSecretPayloadKey] = payload
-	patch.Data[TokenSecretReasonKey] = []byte(hyperv1.NodePoolAsExpectedConditionReason)
-	patch.Data[TokenSecretMessageKey] = []byte("Payload generated successfully")
+	nodePoolUpgradeType, ok := tokenSecret.Annotations[TokenSecretNodePoolUpgradeType]
+	if ok && nodePoolUpgradeType == string(hyperv1.UpgradeTypeReplace) {
```
Comment (enxebre) [inline ignition-server/controllers/tokensecret_controller.go:290]: nit: the ok && is redundant here, personally I find easier to read
```
	patch.Data[TokenSecretPayloadKey] = payload
	nodePoolUpgradeType := tokenSecret.Annotations[TokenSecretNodePoolUpgradeTyp"]
	if nodePoolUpgradeType == string(hyperv1.UpgradeTypeReplace) {
		delete(patch.Data, TokenSecretPayloadKey)
	}
```
just a subject opinion fwiw, no need to change.

Comment (enxebre) [reply ignition-server/controllers/tokensecret_controller.go:290]: Can you please add a testCase here https://github.com/openshift/hypershift/blob/main/ignition-server/controllers/tokensecret_controller_test.go#L47

**Comment by enxebre** [comment]
thanks! looks great other than https://github.com/openshift/hypershift/pull/1873/files#r1025842234
