### PR TITLE
fix(api): Fix deprecated API conversion

### LINKED ISSUE #1988: Cannot update HC cluster configuration from v1alpha1 API
With the support of `v1beta1` APIs, a conversion webhook was introduced. This webhook is not properly converting certain aspects of `v1alpha1` fields in update scenarios.

Currently, any fields in the [`v1alpha1` HC's cluster configuration](https://github.com/openshift/hypershift/blob/d1d6eee44555145f0b805173a37cda5c5c6f9836/api/v1alpha1/hostedcluster_types.go#L257) will not be honored. Instead, it is always preserving the cluster configuration values from the already existing `v1beta1` HC.

This is causing update/upgrade issues when fields in the HC's cluster configuration is altered and applied through the `v1alpha1` API. For example, updating HCs with feature gates specified.

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Please review this change thoroughly. This updates `v1alpha1` --> `v1beta1` conversion logic to ignore reconciling deprecated fields from Hub (raw) to HC conversion. Without this, deprecated cluster config fields were clobbering the supported fields during the conversion round trip.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #1988

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by hasueki** [comment]
@csrwng Please let me know what you think about this PR. I realize it needs a rebase, so I will fix that up along with any additional adjustments.

**Comment by hasueki** [comment]
@csrwng @sjenning Rebased. FWIW, this PR fixes our CI for the most part (IKS we need to adjust to create the webhook TLS at runtime, hence it's failing)

File: api/v1alpha1/zz_conversion.go [hunk 1]
```diff
@@ -172,29 +167,29 @@ func fixupHostedControlPlaneAfterConversion(hcp *HostedControlPlane) error {
...
-func populatedDeprecatedAWSRoles(aws *AWSPlatformSpec) {
+func populateDeprecatedAWSRoles(aws *AWSPlatformSpec) {
 	aws.KubeCloudControllerCreds.Name = convertARNToSecretName(aws.RolesRef.KubeCloudControllerARN)
 	aws.NodePoolManagementCreds.Name = convertARNToSecretName(aws.RolesRef.NodePoolManagementARN)
 	aws.ControlPlaneOperatorCreds.Name = convertARNToSecretName(aws.RolesRef.ControlPlaneOperatorARN)
 	aws.Roles = []AWSRoleCredentials{
 		{
-			ARN:       aws.RolesRef.IngressARN,
-			Namespace: "openshift-ingress-operator",
+			ARN:       aws.RolesRef.NetworkARN,
```
Comment (csrwng) [inline api/v1alpha1/zz_conversion.go:176]: what is the purpose of reordering these?

File: api/v1alpha1/zz_conversion_test.go [hunk 2]
```diff
@@ -76,97 +74,44 @@ func configFuzzer(in *ClusterConfiguration, c fuzz.Continue) {
 		if in.APIServer.Audit.Profile == "" {
 			in.APIServer.Audit.Profile = configv1.DefaultAuditProfileType
 		}
-		in.Items = append(in.Items, runtime.RawExtension{
```
Comment (csrwng) [inline api/v1alpha1/zz_conversion_test.go:79]: Instead of changing these, can you just call populateDeprecated* functions in the fixupHostedCluster functions?
It'd be good to keep this for the HostedControlPlane conversion.

**Comment by csrwng** [comment]
Hey @hasueki a couple of comments, otherwise lgtm

File: api/v1alpha1/zz_conversion.go (hunk 1 above)
Comment (hasueki) [reply api/v1alpha1/zz_conversion.go:176]: It was failing on comparison on unit tests. IIRC, the fuzzer was returning them in alphabetical order by namespace.

**Comment by hasueki** [comment]
@csrwng Updated, PTAL
