### PR TITLE
fix(ho): honor deprecated global config fields

### LINKED ISSUE #1630: Deprecated global config can only be applied once
With recent deprecation of HC's `spec.configuration.items[]` fields, https://github.com/openshift/hypershift/pull/1463, when existing HCs are patched with updates on those fields, the changes will never be applied. This means that this API only supports backward compatibility only on the initial apply.

In our scenario, we have HCs that may look like..
```
apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: "{{ cluster_id }}"
  namespace: "{{ hosted_clusters_namespace }}"
  labels:
    clusterid: "{{ cluster_id }}"
  annotations:
   ...
spec:
  configuration:
    items:
    - apiVersion: config.openshift.io/v1
      kind: FeatureGate
      metadata:
        creationTimestamp: null
      spec:
        customNoUpgrade:
          disabled:
          - ServiceLBNodePortControl
        featureSet: CustomNoUpgrade
...
```
.. when the managing HOs gets updated with the above PR's change and HC gets reconciled, this will get mutated it to..
```
apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: "{{ cluster_id }}"
  namespace: "{{ hosted_clusters_namespace }}"
  labels:
    clusterid: "{{ cluster_id }}"
  annotations:
   ...
spec:
  configuration:
    featureGate:
      customNoUpgrade:
        disabled:
        - ServiceLBNodePortControl
      featureSet: CustomNoUpgrade
...
```

Now, when we conduct any sort of patch updates on `spec.configuration.items[]`, it will never be honored and will continue to use the values that was present at the initial apply.

Note: For IBM Cloud, we have separate update cycles for the HO and its HCs, so we will need to make sure compatibility is not broken between the two, nor dependent on one another.

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Fixes #1630 

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #1630

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [x] This change includes unit tests.

### CODE REVIEW

File: hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go [hunk 1]
```diff
@@ -4526,35 +4526,32 @@ func (r *HostedClusterReconciler) reconcileDeprecatedGlobalConfig(ctx context.Co
...
 	}
-	if gconfig.Scheduler != nil && hc.Spec.Configuration.Scheduler == nil {
+	if gconfig.Scheduler != nil {
 		hc.Spec.Configuration.Scheduler = &gconfig.Scheduler.Spec
 	}
-	if gconfig.Proxy != nil && hc.Spec.Configuration.Proxy == nil {
+	if gconfig.Proxy != nil {
 		hc.Spec.Configuration.Proxy = &gconfig.Proxy.Spec
 	}
 	hc.Spec.Configuration.Items = nil
```
Comment (csrwng) [inline hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: If the unstructured config will still take precedence, then we likely don't want to clear it here

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: Gotcha ok. I'm fine with clearing the older fields, as long as the unstructured config gets get overlaid on top of the new fields on apply. But we can simply not clear too - just didn't know if we wanted to keep this mutating behavior.

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: And also for my clarity, if we don't clear `items[]`, we would still want to populate the new fields?

Comment (csrwng) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: We definitely want to populate the new fields.
The reason I was thinking of not clearing the old fields is that if you have code updating the config there, then you're going to be fighting against the hc controller. One clearing it, the other populating it.

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: > We definitely want to populate the new fields.

Understood!

> The reason I was thinking of not clearing the old fields is that if you have code updating the config there, then you're going to be fighting against the hc controller. One clearing it, the other populating it.

Ah good point, you maybe right there. Ok will update!

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: One more thing! Do we want to keep the ConfigMapRefs and SecretRefs, as well? I see that for the HCP reconcilication, it now parses these info from the new fields https://github.com/openshift/hypershift/blob/704177c8855e34fd53d39d4c9b83696947c09edc/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L1474-L1487

Comment (csrwng) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:4557]: I think it’s fine the way it is

Comment (hasueki) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go]: @csrwng Getting stuck on this one. When I add `hc.Spec.Configuration.Items = nil`, unit tests starts to err with..
```
# hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go:2206

unexpected get error: json: error calling MarshalJSON for type runtime.RawExtension: invalid character 'a' looking for beginning of value
```
Do you happen to have any ideas?

Comment (csrwng) [reply hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go]:
```
serializedAPIServer, err := util.SerializeResource(apiServer, hyperapi.Scheme)
```
This ^^ is serializing the apiserver as yaml, for a RawExtension it needs to be JSON
See https://github.com/openshift/hypershift/blob/main/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L4765-L4781

File: support/globalconfig/globalconfig.go [hunk 2]
```diff
@@ -52,6 +52,11 @@ func ParseGlobalConfig(ctx context.Context, cfg *hyperv1.ClusterConfiguration) (
 		kinds.Insert(gvk.Kind)
 		switch obj := cfgObject.(type) {
 		case *configv1.APIServer:
+			if obj.Spec.Audit.Profile == "" {
+				// Populate kubebuilder default for comparison
+				// https://github.com/openshift/api/blob/f120778bee805ad1a7a4f05a6430332cf5811813/config/v1/types_apiserver.go#L57
+				obj.Spec.Audit.Profile = configv1.DefaultAuditProfileType
+			}
```
Comment (hasueki) [inline support/globalconfig/globalconfig.go:59]: Bit of explanation on this: yaml is decoded as `audit: {}`, but is compared against `audit: { Profile: Default }` because of the default being set.
